### ISSUE TITLE
Use cameras directly instead of using OpenCV

### ISSUE THREAD

**Issue by sr229** [vignetteapp/vignette-camera#69]
Let's face it, OpenCV is **overkill**. Facette requires a Bitmap input anyways so we just need to do the following without relying on any third-party library as much as possible:

- [ ] Open camera devices and pipe to `Memory<T>` as a shared buffer pointer.
- [ ] Output `Bitmap`

**Comment by LeNitrous** [comment]
Relevant documentation for Windows. I believe this should contain everything we need for that platform:
https://docs.microsoft.com/en-us/windows/win32/wia/-wia-startpage

I'll check Linux for later.

**Comment by sr229** [comment]
Relevant for Linux:

- Use `libcamera` API to interface with v4l2 devices
- `libcamera.so` requires P/Invoke
- There are no other implementations so this will have to be done by us and exclusively us.

**Comment by sr229** [comment]
Might need to rethink this since MediaPipe has OpenCV as a hard requirement. I suggest not proceeding here until we can figure out if MediaPipe can be ran without OpenCV (which unfortunately might not be possible).
